### ISSUE TITLE
django-content-settings and django-debug-toolbar conflict

### ISSUE THREAD

**Issue by richardbrockie** [occipital/django-content-settings#128]
Hi,

I've come across what might be a new conflict. I'm sure this was working fine some months ago with earlier versions. Is there something I'm doing wrong?

Python==3.11.10
Django==4.2.17
django-debug-toolbar==4.4.6
django-content-settings==0.29.1

When I am use `django-debug-toolbar` in development together with `django-content-settings` I get the following error when loading any page in my django app:

```
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/richard/VirtualEnvs/ontheday_heroku_v3.11.10/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richard/VirtualEnvs/ontheday_heroku_v3.11.10/lib/python3.11/site-packages/debug_toolbar/middleware.py", line 92, in __call__
    panel.generate_stats(request, response)
  File "/Users/richard/VirtualEnvs/ontheday_heroku_v3.11.10/lib/python3.11/site-packages/debug_toolbar/panels/templates/panel.py", line 201, in generate_stats
    template_data["context_list"] = self.process_context_list(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richard/VirtualEnvs/ontheday_heroku_v3.11.10/lib/python3.11/site-packages/debug_toolbar/panels/templates/panel.py", line 142, in process_context_list
    if hasattr(value, "_wrapped"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richard/VirtualEnvs/ontheday_heroku_v3.11.10/lib/python3.11/site-packages/content_settings/conf.py", line 364, in __getattr__
    prefix, name, suffix = split_attr(value)
                           ^^^^^^^^^^^^^^^^^
  File "/Users/richard/VirtualEnvs/ontheday_heroku_v3.11.10/lib/python3.11/site-packages/content_settings/conf.py", line 149, in split_attr
    assert name.isupper(), f"Invalid attribute name: {value}; name should be uppercase"
```

Link to `django-debug-toolbar`:  https://django-debug-toolbar.readthedocs.io/en/latest/

**Comment by oduvan** [comment]
Good catch.

split_attr should not raise an exception for hasattr.

Thank you

**Comment by oduvan** [comment]
@richardbrockie try `0.29.2`, the new version just released

**Comment by richardbrockie** [comment]
@oduvan `0.29.2` gives the same error as above, this time at line 156 in `content_settings/conf.py`. It was line 149 with the earlier version.

My guess is that `django-debug-toolbar` is adding items to the context contaning "_wrapper" and `django-content-settings` is objecting that it is not upper case as `assert name.isupper()` is failing.

**Comment by richardbrockie** [comment]
I've narrowed the cause to being with a specific panel in `django-debug-toolbar`: 

```
INSTALLED_APPS = ('debug_toolbar', ) + INSTALLED_APPS

MIDDLEWARE += (
    'debug_toolbar.middleware.DebugToolbarMiddleware',
)

DEBUG_TOOLBAR_PANELS = [
    # ...
    'debug_toolbar.panels.templates.TemplatesPanel',    # breaks django-content-settings...
    # ...
]
