### ISSUE TITLE
"Foreign key constraint is incorrectly formed" when migrating database

### ISSUE THREAD

**Issue by justinqian42** [occipital/django-content-settings#65]
Error details:

```
venv) user@macbook prime % ./manage.py migrate       
Operations to perform:
  Apply all migrations: admin, auth, content_settings, contenttypes, django_celery_beat, django_celery_results, inventory, lifecycle, sessions, support
Running migrations:
  Applying content_settings.0001_initial...Traceback (most recent call last):
  File "....../venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "....../venv/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1005, 'Can\'t create table `app_db`.`content_settings_usertagsetting` (errno: 150 "Foreign key constraint is incorrectly formed")')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "....../src/prime/./manage.py", line 22, in <module>
    main()
  File "....../src/prime/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "....../venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "....../venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "....../venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "....../venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 249, in apply_migration
    with self.connection.schema_editor(
  File "....../venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 166, in __exit__
    self.execute(sql)
  File "....../venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "....../venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/cachalot/monkey_patch.py", line 137, in inner
    return original(cursor, sql, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "....../venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "....../venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....../venv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "....../venv/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1005, 'Can\'t create table `app_db`.`content_settings_usertagsetting` (errno: 150 "Foreign key constraint is incorrectly formed")')
```

Environment:

python 3.11.7
django 4.2.10
mariadb 10.11

**Comment by oduvan** [comment]
sounds weird that it fails on Django generated migration

**Comment by fredriknilson** [comment]
I have the same problem.

The id on the usermodel is a UUIDField.

The table is created for me but the migration fails anyway, it think i fails on the creation of the unique_together index.

It fails both on an empty database and a database with tables and data.

**Comment by oduvan** [comment]
Thank you. Will take this one in work.

**Comment by fredriknilson** [comment]
No

I am behind on both Python and Django

python 3.8
django 3.2
mariadb 11.5.2

(i know i realy should be upgrading)

I am in the process of doing a test upgrade to the following and see if i get the same results

python 3.12
django 4.2
mariadb 11.5.2

**Comment by fredriknilson** [comment]
I might have found something

by editing `lib/python3.8/site-packages/content_settings/migrations/0001_initial.py` and by remove
`tag` from `unique_together` it works

migrations.CreateModel(
            name="UserTagSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tag", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                # "unique_together": {("user", "name", "tag")},
                "unique_together": {("user", "name")},
            },
        ),

**Comment by oduvan** [comment]
@fredriknilson I've pushed fixed to master. I change tag field from text to char, to make it available for indexing. We test a bit more tomorrow and release

**Comment by fredriknilson** [comment]
Using master works for me now.

**Comment by oduvan** [comment]
Update to `0.25`
